### ISSUE TITLE
getting unsupported distro on linuxmint 18.1

### ISSUE THREAD

**Issue by SteveDevOps** [anbox/anbox-installer#10]
cat /etc/linuxmint/info

RELEASE=18.1
CODENAME=serena
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 18.1 Serena"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_serena_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_serena_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18.1 Cinnamon 64-bit

**Comment by morphis** [comment]
Mint is now in the list of supported distributions: see https://github.com/anbox/anbox-installer/blob/master/installer.sh#L33

If this still doesn't work for you please reopen and say why.

**Comment by hub2git** [comment]
@SteveDevOps, I'm interested in knowing whether Anbox now works for you. You see, I'm on Mint 18.1 also (but Xfce), and anbox still doesn't work for me.

**Comment by hub2git** [comment]
Dear @SteveDevOps, Could you please reopen this issue because I, a Mint
18.1 user, am having issues.

**Comment by SteveDevOps** [comment]
Sorry, I don't have the reopen option.. I think owner closed it.

https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github

**Comment by hub2git** [comment]
@SteveDevOps, thank you for your reply. Funny that the repo owner
(@morphis) suggests that you, the thread-starter, can reopen an issue.
Perhaps he didn't know that the thread-starter can re-open an issue that he
has closed himself.
