### ISSUE TITLE
Installer does not check essential things before action

### ISSUE THREAD

**Issue by stanislavvv** [anbox/anbox-installer#14]
1) Installer try to exec `sudo snap` in the system without snap (try it on fresh install of Ubuntu 14.04).
May be checked via:

```
[[ -n "$(which snap)" ]] || { 
    echo "snap does not installed - exiting..."
    exit 1
}
```
It must be checked before any apt/dkms/config actions, so if snap does not exists - system will be untouched.

2) Linux Mint Debian Edition still Linux Mint, but it does not contain some ubuntu-specific packages, such as `linux-headers-generic`
I don't know how to check this situation, but on 64-bit debian must be installed `linux-headers-amd64` package.

3) I think, `set -eu` in second line will add some checks of apt-get exit codes. Not only apt-get.

**Comment by morphis** [comment]
@stanislavvv Interested in helping to improve on these things? PRs are welcome!
