### ISSUE TITLE
Error running anbox-installer: execv failed

### ISSUE THREAD

**Issue by amankhoza** [anbox/anbox-installer#22]
After installing the anbox-installer snap, when I try running anbox-installer I get the following error:

execv failed: No such file or directory

I'm running Fedora 24, any ideas?

**Comment by morphis** [comment]
Fedora doesn't support classic snaps which we're using for the anbox-installer snap. However you can use the installer.sh script directly:

```
$ wget -O installer.sh https://raw.githubusercontent.com/anbox/anbox-installer/master/installer.sh
$ bash installer.sh
```

However on Fedora this doesn't help yet as we're still missing support for Fedora which will come soon.
